version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    container_name: game-bot
    command: python3 -m game.main
    tty: true
    depends_on:
      - postgres
    image: 'game-bot'
    environment:
      CONFIG: ./config/local.yaml

  postgres:
    container_name: bot-postgres
    image: postgres:15
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=game

volumes:
  postgres_local_data: {}
