version: '3.7'

services:
  base: &bot-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
    image: 'game-bot'
    environment:
      CONFIG: ./config/local.yaml

  bot:
    <<: *bot-dev
    ports:
      - "8080:8080"
    container_name: game-bot
    command: python3 -m game.main
    tty: true
    depends_on:
      - postgres

  postgres:
    container_name: bot-postgres
    image: postgres:15
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=game

  tools:
    <<: *bot-dev
    command: bash -c "flake8 ./game && mypy ./game && isort ./game"



volumes:
  postgres_local_data: {}
